### ISSUE TITLE
Guibuilder moves selected element while typing a property on the right pane

### ISSUE THREAD

**Issue by superxpro12** [timothycrosley/WebBot#2]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/GuiBuilder/GuiBuilder.py", line 712, in updateProperties
    controller = PropertyController(unicode(item.text(4)), propertyName, propertyType, self)
  File "/usr/local/lib/python2.7/dist-packages/GuiBuilder/GuiBuilder.py", line 95, in **init**
    self.widget = self.createWidget()
  File "/usr/local/lib/python2.7/dist-packages/GuiBuilder/GuiBuilder.py", line 114, in createWidget
    value = self.builder.propertyMap[self.elementKey].get(self.propertyName, None)
KeyError: u'3'

The guibuilder setup
http://imgur.com/xGbklJ5

It moves the selected tree element when typing any two letters. So it moves on the 'a' in 'Za'.

**Comment by timothycrosley** [comment]
Thanks for reporting! I have fixed this in release 0.9.6.
